/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-04-21 12:25:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.10.RELEASE.jar", Long.valueOf(1648026250747L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639219687789L));
    _jspx_dependants.put("jar:file:/D:/Eclipse%20Learning/Spring_MVC_Project_Final/src/main/wtpwebapps/Spring_MVC_Project_Final/WEB-INF/lib/spring-webmvc-5.2.10.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1603780778000L));
    _jspx_dependants.put("jar:file:/D:/Eclipse%20Learning/Spring_MVC_Project_Final/src/main/wtpwebapps/Spring_MVC_Project_Final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath_005fcssClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005foption_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005finput_0026_005ftype_005fpath_005fmultiple_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005ftextarea_0026_005frows_005fpath_005fid_005fcssClass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath_005fcssClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005foption_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005finput_0026_005ftype_005fpath_005fmultiple_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005ftextarea_0026_005frows_005fpath_005fid_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005faction.release();
    _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath_005fcssClass.release();
    _005fjspx_005ftagPool_005fspring_005foption_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005finput_0026_005ftype_005fpath_005fmultiple_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005ftextarea_0026_005frows_005fpath_005fid_005fcssClass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Add Category</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/include/management/css-page.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/include/management/js-page.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body\r\n");
      out.write("	class=\"page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-sidebar-color logo-dark\">\r\n");
      out.write("	<div class=\"page-wrapper\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/include/management/header-page.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"page-container\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/include/management/menu-page.jsp", out, false);
      out.write("\r\n");
      out.write("			<!-- start page content -->\r\n");
      out.write("			<div class=\"page-content-wrapper\">\r\n");
      out.write("				<div class=\"page-content\">\r\n");
      out.write("					<div class=\"page-bar\">\r\n");
      out.write("						<div class=\"page-title-breadcrumb\">\r\n");
      out.write("							<div class=\" pull-left\">\r\n");
      out.write("								<div class=\"page-title\">Add Room Category</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ol class=\"breadcrumb page-breadcrumb pull-right\">\r\n");
      out.write("								<li><i class=\"fa fa-home\"></i>&nbsp;<a class=\"parent-item\"\r\n");
      out.write("									href=\"index.html\">Home</a>&nbsp;<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li><a class=\"parent-item\" href=\"\">Room Category</a>&nbsp;<i\r\n");
      out.write("									class=\"fa fa-angle-right\"></i></li>\r\n");
      out.write("								<li class=\"active\">Add Room Category</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-12\">\r\n");
      out.write("							<div class=\"card-box\">\r\n");
      out.write("								<div class=\"card-head\">\r\n");
      out.write("									<header>Add Room Category</header>\r\n");
      out.write("									<button id=\"panel-button\"\r\n");
      out.write("										class=\"mdl-button mdl-js-button mdl-button--icon pull-right\"\r\n");
      out.write("										data-upgraded=\",MaterialButton\">\r\n");
      out.write("										<i class=\"material-icons\">more_vert</i>\r\n");
      out.write("									</button>\r\n");
      out.write("									<ul\r\n");
      out.write("										class=\"mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect\"\r\n");
      out.write("										data-mdl-for=\"panel-button\">\r\n");
      out.write("										<li class=\"mdl-menu__item\"><i class=\"material-icons\">assistant_photo</i>Action</li>\r\n");
      out.write("										<li class=\"mdl-menu__item\"><i class=\"material-icons\">print</i>Another\r\n");
      out.write("											action</li>\r\n");
      out.write("										<li class=\"mdl-menu__item\"><i class=\"material-icons\">favorite</i>Something\r\n");
      out.write("											else here</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								");
      //  spring:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_spring_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_spring_005fform_005f0_reused = false;
      try {
        _jspx_th_spring_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fform_005f0.setParent(null);
        // /WEB-INF/pages/admin/addCategory.jsp(58,8) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fform_005f0.setAction("doAddCategory");
        // /WEB-INF/pages/admin/addCategory.jsp(58,8) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fform_005f0.setMethod("post");
        // /WEB-INF/pages/admin/addCategory.jsp(58,8) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fform_005f0.setModelAttribute("roomCategory");
        // /WEB-INF/pages/admin/addCategory.jsp(58,8) name = enctype type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fform_005f0.setEnctype("multipart/form-data");
        int[] _jspx_push_body_count_spring_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fform_005f0 = _jspx_th_spring_005fform_005f0.doStartTag();
          if (_jspx_eval_spring_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("									<div class=\"card-body row\">\r\n");
              out.write("\r\n");
              out.write("										<div class=\"col-lg-6 p-t-20\">\r\n");
              out.write("											<div\r\n");
              out.write("												class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width\">\r\n");
              out.write("												");
              if (_jspx_meth_spring_005finput_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("												");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f0_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/pages/admin/addCategory.jsp(67,12) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f0.setPath("name");
                int[] _jspx_push_body_count_spring_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f0 = _jspx_th_spring_005ferrors_005f0.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005ferrors_005f0);
                _jspx_th_spring_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f0_reused);
              }
              out.write("\r\n");
              out.write("												<label class=\"mdl-textfield__label\">Room Name</label>\r\n");
              out.write("											</div>\r\n");
              out.write("										</div>\r\n");
              out.write("\r\n");
              out.write("										<div class=\"col-lg-6 p-t-20\">\r\n");
              out.write("											<div\r\n");
              out.write("												class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width\">\r\n");
              out.write("												");
              if (_jspx_meth_spring_005finput_005f1(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("												");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f1_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/pages/admin/addCategory.jsp(77,12) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f1.setPath("size");
                int[] _jspx_push_body_count_spring_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f1 = _jspx_th_spring_005ferrors_005f1.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005ferrors_005f1);
                _jspx_th_spring_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f1_reused);
              }
              out.write("\r\n");
              out.write("												<label class=\"mdl-textfield__label\">Room Size</label> <span\r\n");
              out.write("													class=\"mdl-textfield__error\">Number required!</span>\r\n");
              out.write("											</div>\r\n");
              out.write("										</div>\r\n");
              out.write("\r\n");
              out.write("										<div class=\"col-lg-6 p-t-20\">\r\n");
              out.write("											<div\r\n");
              out.write("												class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width\">\r\n");
              out.write("												");
              if (_jspx_meth_spring_005finput_005f2(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("												");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f2 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f2_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f2.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/pages/admin/addCategory.jsp(88,12) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f2.setPath("bedInfo");
                int[] _jspx_push_body_count_spring_005ferrors_005f2 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f2 = _jspx_th_spring_005ferrors_005f2.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f2[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f2.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f2.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005ferrors_005f2);
                _jspx_th_spring_005ferrors_005f2_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f2_reused);
              }
              out.write("\r\n");
              out.write("												<label class=\"mdl-textfield__label\">Type Bed</label>\r\n");
              out.write("											</div>\r\n");
              out.write("										</div>\r\n");
              out.write("										<div class=\"col-lg-6 p-t-20\">\r\n");
              out.write("											<div\r\n");
              out.write("												class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width\">\r\n");
              out.write("												");
              if (_jspx_meth_spring_005finput_005f3(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("												");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f3 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f3_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f3.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/pages/admin/addCategory.jsp(97,12) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f3.setPath("capacity");
                int[] _jspx_push_body_count_spring_005ferrors_005f3 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f3 = _jspx_th_spring_005ferrors_005f3.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f3[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f3.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f3.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005ferrors_005f3);
                _jspx_th_spring_005ferrors_005f3_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f3_reused);
              }
              out.write("\r\n");
              out.write("												<label class=\"mdl-textfield__label\">Capacity</label>\r\n");
              out.write("											</div>\r\n");
              out.write("										</div>\r\n");
              out.write("\r\n");
              out.write("										<div class=\"col-lg-6 p-t-20\">\r\n");
              out.write("											<div\r\n");
              out.write("												class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width\">\r\n");
              out.write("												");
              if (_jspx_meth_spring_005finput_005f4(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("												");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f4 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f4_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f4.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/pages/admin/addCategory.jsp(107,12) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f4.setPath("price");
                int[] _jspx_push_body_count_spring_005ferrors_005f4 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f4 = _jspx_th_spring_005ferrors_005f4.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f4[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f4.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f4.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005ferrors_005f4);
                _jspx_th_spring_005ferrors_005f4_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f4_reused);
              }
              out.write("\r\n");
              out.write("												<label class=\"mdl-textfield__label\">Price</label> <span\r\n");
              out.write("													class=\"mdl-textfield__error\">Number required!</span>\r\n");
              out.write("											</div>\r\n");
              out.write("										</div>\r\n");
              out.write("\r\n");
              out.write("										<div class=\"col-lg-6 p-t-20\">\r\n");
              out.write("											<div\r\n");
              out.write("												class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width\">\r\n");
              out.write("												<div class=\"form-group\">\r\n");
              out.write("													");
              //  spring:select
              org.springframework.web.servlet.tags.form.SelectTag _jspx_th_spring_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath_005fcssClass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
              boolean _jspx_th_spring_005fselect_005f0_reused = false;
              try {
                _jspx_th_spring_005fselect_005f0.setPageContext(_jspx_page_context);
                _jspx_th_spring_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/pages/admin/addCategory.jsp(117,13) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005fselect_005f0.setPath("status");
                // /WEB-INF/pages/admin/addCategory.jsp(117,13) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005fselect_005f0.setCssClass("form-control");
                int[] _jspx_push_body_count_spring_005fselect_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005fselect_005f0 = _jspx_th_spring_005fselect_005f0.doStartTag();
                  if (_jspx_eval_spring_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    do {
                      out.write("\r\n");
                      out.write("														");
                      //  spring:option
                      org.springframework.web.servlet.tags.form.OptionTag _jspx_th_spring_005foption_005f0 = (org.springframework.web.servlet.tags.form.OptionTag) _005fjspx_005ftagPool_005fspring_005foption_0026_005fvalue.get(org.springframework.web.servlet.tags.form.OptionTag.class);
                      boolean _jspx_th_spring_005foption_005f0_reused = false;
                      try {
                        _jspx_th_spring_005foption_005f0.setPageContext(_jspx_page_context);
                        _jspx_th_spring_005foption_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fselect_005f0);
                        // /WEB-INF/pages/admin/addCategory.jsp(118,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                        _jspx_th_spring_005foption_005f0.setValue("");
                        int[] _jspx_push_body_count_spring_005foption_005f0 = new int[] { 0 };
                        try {
                          int _jspx_eval_spring_005foption_005f0 = _jspx_th_spring_005foption_005f0.doStartTag();
                          if (_jspx_eval_spring_005foption_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.Object value = null;
                            java.lang.String displayValue = null;
                            if (_jspx_eval_spring_005foption_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              _jspx_push_body_count_spring_005foption_005f0[0]++;
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spring_005foption_005f0);
                            }
                            value = (java.lang.Object) _jspx_page_context.findAttribute("value");
                            displayValue = (java.lang.String) _jspx_page_context.findAttribute("displayValue");
                            do {
                              out.write("Select");
                              int evalDoAfterBody = _jspx_th_spring_005foption_005f0.doAfterBody();
                              value = (java.lang.Object) _jspx_page_context.findAttribute("value");
                              displayValue = (java.lang.String) _jspx_page_context.findAttribute("displayValue");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_spring_005foption_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              _jspx_push_body_count_spring_005foption_005f0[0]--;
                            }
                          }
                          if (_jspx_th_spring_005foption_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                        } catch (java.lang.Throwable _jspx_exception) {
                          while (_jspx_push_body_count_spring_005foption_005f0[0]-- > 0)
                            out = _jspx_page_context.popBody();
                          _jspx_th_spring_005foption_005f0.doCatch(_jspx_exception);
                        } finally {
                          _jspx_th_spring_005foption_005f0.doFinally();
                        }
                        _005fjspx_005ftagPool_005fspring_005foption_0026_005fvalue.reuse(_jspx_th_spring_005foption_005f0);
                        _jspx_th_spring_005foption_005f0_reused = true;
                      } finally {
                        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005foption_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005foption_005f0_reused);
                      }
                      out.write("\r\n");
                      out.write("														");
                      if (_jspx_meth_spring_005foptions_005f0(_jspx_th_spring_005fselect_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fselect_005f0))
                        return;
                      out.write("\r\n");
                      out.write("													");
                      int evalDoAfterBody = _jspx_th_spring_005fselect_005f0.doAfterBody();
                      if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                    } while (true);
                  }
                  if (_jspx_th_spring_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005fselect_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005fselect_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005fselect_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath_005fcssClass.reuse(_jspx_th_spring_005fselect_005f0);
                _jspx_th_spring_005fselect_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fselect_005f0_reused);
              }
              out.write("\r\n");
              out.write("													");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f5 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f5_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f5.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/pages/admin/addCategory.jsp(121,13) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f5.setPath("status");
                int[] _jspx_push_body_count_spring_005ferrors_005f5 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f5 = _jspx_th_spring_005ferrors_005f5.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f5[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f5.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f5.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005ferrors_005f5);
                _jspx_th_spring_005ferrors_005f5_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f5_reused);
              }
              out.write("\r\n");
              out.write("												</div>\r\n");
              out.write("											</div>\r\n");
              out.write("										</div>\r\n");
              out.write("\r\n");
              out.write("										<label class=\"control-label col-md-3\">Upload Room\r\n");
              out.write("											Photos</label>\r\n");
              out.write("										<div class=\"col-lg-12 p-t-20\">\r\n");
              out.write("											");
              if (_jspx_meth_spring_005finput_005f5(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("										</div>\r\n");
              out.write("										<div class=\"col-lg-12 p-t-20\">\r\n");
              out.write("											<div class=\"mdl-textfield mdl-js-textfield txt-full-width\">\r\n");
              out.write("												");
              if (_jspx_meth_spring_005ftextarea_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("												");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f6 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f6_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f6.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/pages/admin/addCategory.jsp(136,12) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f6.setPath("description");
                int[] _jspx_push_body_count_spring_005ferrors_005f6 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f6 = _jspx_th_spring_005ferrors_005f6.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f6[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f6.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f6.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005ferrors_005f6);
                _jspx_th_spring_005ferrors_005f6_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f6, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f6_reused);
              }
              out.write("\r\n");
              out.write("												<label class=\"mdl-textfield__label\" for=\"text7\">Description</label>\r\n");
              out.write("											</div>\r\n");
              out.write("										</div>\r\n");
              out.write("										<div class=\"col-lg-12 p-t-20 text-center\">\r\n");
              out.write("											<input type=\"submit\" value=\"Add\"\r\n");
              out.write("												class=\"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink\" />\r\n");
              out.write("											<a href=\"viewCategory\">\r\n");
              out.write("												<button type=\"button\"\r\n");
              out.write("													class=\"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default\">Cancel</button>\r\n");
              out.write("											</a>\r\n");
              out.write("										</div>\r\n");
              out.write("									</div>\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005faction.reuse(_jspx_th_spring_005fform_005f0);
        _jspx_th_spring_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- end page content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f0_reused = false;
    try {
      _jspx_th_spring_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/pages/admin/addCategory.jsp(65,12) null
      _jspx_th_spring_005finput_005f0.setDynamicAttribute(null, "class", "mdl-textfield__input");
      // /WEB-INF/pages/admin/addCategory.jsp(65,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f0.setPath("name");
      // /WEB-INF/pages/admin/addCategory.jsp(65,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f0.setId("txtRoomNo");
      int[] _jspx_push_body_count_spring_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f0 = _jspx_th_spring_005finput_005f0.doStartTag();
        if (_jspx_th_spring_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_spring_005finput_005f0);
      _jspx_th_spring_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f1_reused = false;
    try {
      _jspx_th_spring_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/pages/admin/addCategory.jsp(75,12) null
      _jspx_th_spring_005finput_005f1.setDynamicAttribute(null, "class", "mdl-textfield__input");
      // /WEB-INF/pages/admin/addCategory.jsp(75,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f1.setPath("size");
      // /WEB-INF/pages/admin/addCategory.jsp(75,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f1.setId("txtRoomNo");
      // /WEB-INF/pages/admin/addCategory.jsp(75,12) null
      _jspx_th_spring_005finput_005f1.setDynamicAttribute(null, "pattern", "-?[0-9]*(\\[0-9]+)?");
      int[] _jspx_push_body_count_spring_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f1 = _jspx_th_spring_005finput_005f1.doStartTag();
        if (_jspx_th_spring_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_spring_005finput_005f1);
      _jspx_th_spring_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f2_reused = false;
    try {
      _jspx_th_spring_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/pages/admin/addCategory.jsp(86,12) null
      _jspx_th_spring_005finput_005f2.setDynamicAttribute(null, "class", "mdl-textfield__input");
      // /WEB-INF/pages/admin/addCategory.jsp(86,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f2.setPath("bedInfo");
      // /WEB-INF/pages/admin/addCategory.jsp(86,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f2.setId("txtRoomNo");
      int[] _jspx_push_body_count_spring_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f2 = _jspx_th_spring_005finput_005f2.doStartTag();
        if (_jspx_th_spring_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_spring_005finput_005f2);
      _jspx_th_spring_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f3_reused = false;
    try {
      _jspx_th_spring_005finput_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/pages/admin/addCategory.jsp(95,12) null
      _jspx_th_spring_005finput_005f3.setDynamicAttribute(null, "class", "mdl-textfield__input");
      // /WEB-INF/pages/admin/addCategory.jsp(95,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f3.setPath("capacity");
      // /WEB-INF/pages/admin/addCategory.jsp(95,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f3.setId("txtRoomNo");
      int[] _jspx_push_body_count_spring_005finput_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f3 = _jspx_th_spring_005finput_005f3.doStartTag();
        if (_jspx_th_spring_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_spring_005finput_005f3);
      _jspx_th_spring_005finput_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f4_reused = false;
    try {
      _jspx_th_spring_005finput_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/pages/admin/addCategory.jsp(105,12) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f4.setCssClass("mdl-textfield__input");
      // /WEB-INF/pages/admin/addCategory.jsp(105,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f4.setPath("price");
      // /WEB-INF/pages/admin/addCategory.jsp(105,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f4.setId("txtRoomNo");
      // /WEB-INF/pages/admin/addCategory.jsp(105,12) null
      _jspx_th_spring_005finput_005f4.setDynamicAttribute(null, "pattern", "-?[0-9]*(\\.[0-9]+)?");
      int[] _jspx_push_body_count_spring_005finput_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f4 = _jspx_th_spring_005finput_005f4.doStartTag();
        if (_jspx_th_spring_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpattern_005fpath_005fid_005fcssClass_005fnobody.reuse(_jspx_th_spring_005finput_005f4);
      _jspx_th_spring_005finput_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005foptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fselect_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:options
    org.springframework.web.servlet.tags.form.OptionsTag _jspx_th_spring_005foptions_005f0 = (org.springframework.web.servlet.tags.form.OptionsTag) _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody.get(org.springframework.web.servlet.tags.form.OptionsTag.class);
    boolean _jspx_th_spring_005foptions_005f0_reused = false;
    try {
      _jspx_th_spring_005foptions_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005foptions_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fselect_005f0);
      // /WEB-INF/pages/admin/addCategory.jsp(119,14) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005foptions_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005foptions_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005foptions_005f0 = _jspx_th_spring_005foptions_005f0.doStartTag();
        if (_jspx_th_spring_005foptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005foptions_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005foptions_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005foptions_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody.reuse(_jspx_th_spring_005foptions_005f0);
      _jspx_th_spring_005foptions_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005foptions_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005foptions_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f5 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005ftype_005fpath_005fmultiple_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f5_reused = false;
    try {
      _jspx_th_spring_005finput_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/pages/admin/addCategory.jsp(129,11) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f5.setPath("images");
      // /WEB-INF/pages/admin/addCategory.jsp(129,11) null
      _jspx_th_spring_005finput_005f5.setDynamicAttribute(null, "type", "file");
      // /WEB-INF/pages/admin/addCategory.jsp(129,11) null
      _jspx_th_spring_005finput_005f5.setDynamicAttribute(null, "multiple", "multiple");
      // /WEB-INF/pages/admin/addCategory.jsp(129,11) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f5.setCssClass("dropzone");
      int[] _jspx_push_body_count_spring_005finput_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f5 = _jspx_th_spring_005finput_005f5.doStartTag();
        if (_jspx_th_spring_005finput_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005ftype_005fpath_005fmultiple_005fcssClass_005fnobody.reuse(_jspx_th_spring_005finput_005f5);
      _jspx_th_spring_005finput_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005ftextarea_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:textarea
    org.springframework.web.servlet.tags.form.TextareaTag _jspx_th_spring_005ftextarea_005f0 = (org.springframework.web.servlet.tags.form.TextareaTag) _005fjspx_005ftagPool_005fspring_005ftextarea_0026_005frows_005fpath_005fid_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.TextareaTag.class);
    boolean _jspx_th_spring_005ftextarea_005f0_reused = false;
    try {
      _jspx_th_spring_005ftextarea_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005ftextarea_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/pages/admin/addCategory.jsp(134,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftextarea_005f0.setPath("description");
      // /WEB-INF/pages/admin/addCategory.jsp(134,12) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftextarea_005f0.setCssClass("mdl-textfield__input");
      // /WEB-INF/pages/admin/addCategory.jsp(134,12) name = rows type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftextarea_005f0.setRows("3");
      // /WEB-INF/pages/admin/addCategory.jsp(134,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftextarea_005f0.setId("education");
      int[] _jspx_push_body_count_spring_005ftextarea_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005ftextarea_005f0 = _jspx_th_spring_005ftextarea_005f0.doStartTag();
        if (_jspx_th_spring_005ftextarea_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005ftextarea_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005ftextarea_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005ftextarea_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005ftextarea_0026_005frows_005fpath_005fid_005fcssClass_005fnobody.reuse(_jspx_th_spring_005ftextarea_005f0);
      _jspx_th_spring_005ftextarea_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ftextarea_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005ftextarea_005f0_reused);
    }
    return false;
  }
}
